  version: "3.9"
  services:
    app:
      image: legin04/rails-app
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWD: postgres
        POSTGRES_HOST: db
      ports:
        - 3000:3000
    db:
      image: postgres:alpine
      environment:
        POSTGRES_PASSWORD: postgres